version: '3'

services:

  app:
    image: node:latest
    container_name: 'app'
    environment:
      - PORT=5050
      - TOKEN=CHANGE_THIS
      - MONGODB_URI=mongodb://mongodb:27017/improved-github-analytics
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
     - 5050:5050
    command: npm start
    links:
      - mongodb
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/home/node/app
      - MONGO_LOG_DIR=/home/node/app
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
        - 27017:27017
    command: mongod

